### ISSUE TITLE
ひとこと more common reading than 一言[いちごん;h] 

### ISSUE THREAD

**Issue by shanrauf** [mass-immersion-approach/MIA-Japanese-Add-on#13]
#### Nature of issue?

- Found a bug

#### Details about the bug:
For example: `最後[さいご;a] の 一言[いちごん;h] が 余計[よけい;h] だ と は 思[おも,おもう;k2]う 。`

**Comment by LucasMIA** [comment]
The overwrite rules feature has been implemented to deal with parsing errors.
