### ISSUE TITLE
上がる sometimes does not get parsed correctly

### ISSUE THREAD

**Issue by shanrauf** [mass-immersion-approach/MIA-Japanese-Add-on#14]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
By itself, 上がる gets parsed correctly, but in the following sentence, it does not:
` ガソリン[;h] の 値段[ねだん;h] が また上[またがみ;h] がり[;k1] まし[;h] た。`

**Comment by LucasMIA** [comment]
The overwrite rules feature has been implemented to deal with parsing errors.
