### ISSUE TITLE
Should be はんする or かえす depending on context

### ISSUE THREAD

**Issue by shanrauf** [mass-immersion-approach/MIA-Japanese-Add-on#15]
#### Nature of issue?
- Found a bug

#### Details about the bug: 
By itself, 返す is parsed as かえす, but in the following case, it should be はんする:
`専門家[せんもんか;h] の 予想[よそう;h] に 反[そら,そらす;k2]して 、 景気[けいき;h] は 回復[かいふく;h] し[,する;h] 始[はじ,はじめる;h]めた 。`

**Comment by LucasMIA** [comment]
The overwrite rules feature has been implemented to deal with parsing errors.
