### ISSUE TITLE
来る is parsed incorrectly in most sentences it appears in

### ISSUE THREAD

**Issue by shanrauf** [mass-immersion-approach/MIA-Japanese-Add-on#16]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
For example: `フランス[;h] を 横[よこ;h] に 行[い,いく;h]ったり 来[く,くる;k1]たり する[,する;h] 。`

**Comment by LucasMIA** [comment]
The overwrite rules feature has been implemented to deal with parsing errors.
