### ISSUE TITLE
Parsing error with くれる

### ISSUE THREAD

**Issue by shanrauf** [mass-immersion-approach/MIA-Japanese-Add-on#20]
#### Nature of issue?
- Found a bug

#### Details about the bug: 
For example: `ちょっと[;o] これ[;h]   解[と,とく;k1]いて みて[,みる;k1] くれ[,くれる;h,o] る ？ くれ[,くれる;h,o] る`

**Comment by LucasMIA** [comment]
The overwrite rules feature has been implemented to deal with parsing errors.
