### ISSUE TITLE
とおり vs どおり parsing

### ISSUE THREAD

**Issue by shanrauf** [mass-immersion-approach/MIA-Japanese-Add-on#23]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Should be どおり:
言葉[ことば;o] 通[とお;o]り 単純[たんじゅん;h] な 意味[いみ;a] で 分[わ,わかり;o]かり やすい[,やすい;k2] 。

**Comment by LucasMIA** [comment]
The overwrite rules feature has been implemented to deal with parsing errors.
