### ISSUE TITLE
誰 parsing error

### ISSUE THREAD

**Issue by shanrauf** [mass-immersion-approach/MIA-Japanese-Add-on#25]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Should be だれ, not だ. 
Example: 俺[おれ;h] の 稽古[けいこ;a] は 誰[た;a]が つけて[,つける;k2] くれ[,くれる;h,o] る ん だ よ

**Comment by LucasMIA** [comment]
The overwrite rules feature has been implemented to deal with parsing errors.
