### ISSUE TITLE
Parsing error with 摘まむ

### ISSUE THREAD

**Issue by z000-z** [mass-immersion-approach/MIA-Japanese-Add-on#31]
> 
> #### Nature of issue?
> 
>     * Found a bug
> 
> 
> #### Details about the bug:
> 
> For example: `靴下[くつした;n2,o] を 干[ほ,ほす;k1]す 時[とき;o] は 爪先[つまさき;h] を 摘[つま,つまむ;h]ま まな[;a] い と それ[;h] だ と ゴム[;a] 伸[の,のび;o]び ちゃう でしょ`

**Comment by LucasMIA** [comment]
The overwrite rules feature has been implemented to deal with parsing errors.
