### ISSUE TITLE
Error on Startup After Fresh Install of the MIA Add-on

### ISSUE THREAD

**Issue by harkdand** [mass-immersion-approach/MIA-Japanese-Add-on#32]
**Environment:**
  - OS: Arch Linux

**Description:**
I get this error when launching Anki:
https://puu.sh/EhZku/ed3f451bca.png

**Comment by shanrauf** [comment]
@harkdand There is limited support right now for Linux, but we're working to add support for it.

**Comment by mvf** [comment]
Looks like you're missing `libQt5Svg.so.5`. Try installing the `qt5-svg` package.

**Comment by omerta14** [comment]
I'm experiencing the same error on windows 10. Mvf could you please elaborate on how someone would locate and install these items. Thanks in advance.

**Comment by mvf** [comment]
@omerta14 On Windows, `QtSvg` is shipped with Anki, so it should Just Work™. I suspect you are having a different problem. Are you sure you're running Anki 2.1.x? If so, feel free to post the error message.

**Comment by omerta14** [comment]
Um yeh quite sure I am. I updated anki to the latest version today in an attempt to fix the issue. I've attached a screenshot of the error.
![mia japanese add on error](https://user-images.githubusercontent.com/55432292/65027825-5c59b380-d97e-11e9-8063-d12d0d396108.png)

**Comment by mvf** [comment]
@omerta14 Okay, your problem _is_ slightly different. The OP seems to be missing the native `QtSvg` library, you seem to be missing the `QtSvg` Python bindings.

Inside the folder with `anki.exe`, there should be a folder `PyQt5`. In there should be a file `QtSvg.pyd`. On my machine (Anki 2.1.15) it is 113,152 bytes. Deleting it triggers the error you posted. `.pyd` files are DLLs, so maybe it got removed by an overzealous antivirus.

**Comment by omerta14** [comment]
Ok so, I assume by anki.exe you mean the anki application?  The folder that houses the anki app ( to find it I right clicked the anki shortcut then clicked on the option " open file location " is that correct? ) doesn't seem to have a folder by the name of PyQt5 or a file named anki.exe exactly . I've will post a screenshot of the folder in question. btw thanks for taking a look I really appreciate it.

**Comment by omerta14** [comment]
There are multiple files that start with PyQt5 though no folder.

![anki folder](https://user-images.githubusercontent.com/55432292/65037459-16f2b180-d991-11e9-8243-b610061711e0.png)

**Comment by mvf** [comment]
@omerta14 Happy to help. Your screenshot explains everything.

The 32-bit "alternate" version of Anki you are running ships the native `Qt5Svg.dll`, but not the Python bindings (`PyQt5.QtSvg.pyd`). I'm not aware of an easy way to procure these. It probably involves doing something close to building/packaging Anki.

If you're on 64-bit Windows, switching to the "standard" Anki version will fix your problem. If you're stuck on 32-bit Windows for some reason, you might have to get creative (e.g. Linux VM, X11 forwarding, ...).

You could report this to [Anki upstream](https://anki.tenderapp.com/discussions/ankidesktop), they can probably fix it quite easily. I don't think it's an Anki _bug_ though, because `QtSvg` doesn't seem to be a dependency of Anki itself.

**Comment by omerta14** [comment]
Seems as through I'm stuck on 32-bit as I simply don't have the hard drive space to install the 64-bit version of windows. I just want to say thanks for taking time out of your day to help. It was greatly appreciated. If anyone knows how fix the issue on the 32-bit version of windows I'd be willing to give it a shot.

**Comment by jamesrwaugh** [comment]
FWIW, I fixed this on Ubuntu by installing `python3-pyqt5.qtsvg`. `sudo apt-get install python3-pyqt5.qtsvg` . It looks like an issue of if this is shipped or not on various platforms by Anki.

**Comment by omerta14** [comment]
Do you know if something similar can be on Windows? The creator of anki said it'll be fixed within the next update but it'll be a few weeks off at the very least

**Comment by mvf** [comment]
@omerta14 Might want to check [your thread](https://anki.tenderapp.com/discussions/ankidesktop/35990-32-bit-of-anki-missing-python-binding-pyqt5qtsvgpyd) on the Anki forums. Spoiler alert: It's fixed in the latest beta. :wink:

**Comment by omerta14** [comment]
Thanks mvf you're an absolute legend if it wasn't for you I'd have no idea there had been a fix, or what the issue was in the first place, or where to have it resolved for that matter. I'll let you know if works.

**Comment by omerta14** [comment]
It worked!!
