### ISSUE TITLE
壊し方 parsing error

### ISSUE THREAD

**Issue by shanrauf** [mass-immersion-approach/MIA-Japanese-Add-on#34]
でも[;a] 　 その場[そのば;h,o] 所[ところ;h] と   壊[こわ,こわす;k2]し 方[ほう;a] が 分[わ,わかる;k2]からない 。
Should be こわしかた (壊し方)

**Comment by LucasMIA** [comment]
The overwrite rules feature has been implemented to deal with parsing errors.
