### ISSUE TITLE
[feature request] showing furigana for one word (e.g.TargetMorph) only

### ISSUE THREAD

**Issue by Duckerl** [mass-immersion-approach/MIA-Japanese-Add-on#39]
**Type:**
  - [ ] bug
  - [x] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Win & Android

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
This should be a feature for introducing new words. 

Imagine you have an example sentence in your expression field with a Target word in it you ought to learn (e.g. from a vocab list for japanese class). 
母は私に**風呂場**の掃除をさせた。
In this case I am introduced to the word ふろば, bathroom for the first time _for that I should not know the reading_ yet. 
However, with the current MIA Addon, I can only read unknown (kanji) words with advanced kanji reading skills or by clicking **風呂場** to learn the reading & pitch accent.

By showing _furigana_ on default for the _unknown word_, with the reading certainly _unknown too_, you can save one click (especially on mobile devices) and would allow faster acquiring of new words.
And after a couple of times (e.g. it reaches `mature`) you could switches to show just pure Kanji. 

This might only seem like a small feature but would make the MIA Addon a more universal all-in-all
experience.

**Comment by LucasMIA** [comment]
We have other projects that take priority to this but thanks for the idea.
