### ISSUE TITLE
Japanese Settings window displays strange

### ISSUE THREAD

**Issue by p2635** [mass-immersion-approach/MIA-Japanese-Add-on#40]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
 - OS: Kubuntu 19.04
 - Display: 1920 x 1080
Let me know if you need more info 

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
When I open Japanese settings, it appears like this for me:
![image](https://user-images.githubusercontent.com/4522927/67982557-d6868480-fc1a-11e9-9240-1c2e0010be6e.png)

**Comment by LucasMIA** [comment]
Linux is not officially supported. Feel free to open a pr to fix these issues on the platform.
