### ISSUE TITLE
bad historical conversion

### ISSUE THREAD

**Issue by grenzionky** [mass-immersion-approach/MIA-Japanese-Add-on#41]
**Type:**
  - [x] bug  
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Manjaro Linux x86_64 
  - Host: 13Z970-A.AAS5U1 0.1 
  - Kernel: 5.3.7-2-MANJARO 
  - WM: awesome 

but this has nothing to do with my environment

**Going to open a PR:**
  - [ ] yes
  - [x] no, cuz im not sure how it was set up. but if someone can tell me, then ill know for the future what to do

**Description:**
Historical Conversion converts `character` into `kana outputted` instead of `kana expected`:

| character | kana outputted | kana expected |
|-----------|----------------|---------------|
| 上        | ジョウ         | ジヤウ        |
| 上        | ウエ           | ウヘ          |
| 情        | ジョウ         | ジヤウ        |
|  繋 |  繋 | 繫 |
| 漢 | 漢 | 漢 |
| 今一 | ヰマイチ | イマイチ |
| 噛 | 噛 | 嚙 |

**Comment by LucasMIA** [comment]
Historical conversion is more of a gimmick feature than anything, we do not plan to invest time into making it work perfectly.
