### ISSUE TITLE
inconsistent conversion

### ISSUE THREAD

**Issue by grenzionky** [mass-immersion-approach/MIA-Japanese-Add-on#42]
**Type:**
  - [x] bug  
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Manjaro Linux x86_64 
  - Host: 13Z970-A.AAS5U1 0.1 
  - Kernel: 5.3.7-2-MANJARO 
  - WM: awesome 

but this has nothing to do with my environment

**Going to open a PR:**
  - [ ] yes
  - [x] no, cuz im not sure how it was set up. but if someone can tell me, then ill know for the future what to do

**Description:**
The conversion to the old japanese spelling system gives inconsistent conversions.

![image](https://user-images.githubusercontent.com/13357949/69167362-d6173600-0ac2-11ea-90d9-2442a95661d5.png)

the upper line is `display-type="kanji"` and the lower 2 lines are both `display-type="coloredkanjireading"`

the upper line converts ヨウ to ヤウ, but on the second line it doesnt.  
on the third it converts 今一 to ヰマイチ even though いま was never ゐま

**Comment by LucasMIA** [comment]
Historical conversion is more of a gimmick feature than anything, we do not plan to invest time into making it work perfectly.
