### ISSUE TITLE
Clash with "multiple windows" add-on

### ISSUE THREAD

**Issue by Marth68** [mass-immersion-approach/MIA-Japanese-Add-on#43]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Linux (Debian Buster)
  - Anki: 2.1.8

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
When the "[Opening the same window multiple time[s]](https://ankiweb.net/shared/info/354407385)" add-on is installed and in its default configuration, audio generation (語) does not work: No [sound:...] is placed in the target audio field. After uninstalling the referenced add-on, the problem goes away, but it would be nice if it could be used in parallel to the MIA Japanese add-on.

**Comment by LucasMIA** [comment]
We unfortunately will not be able to offer support or a guarantee that our add-ons will work with all other add-ons on AnkiWeb. We do however strive to ensure cross compatibility with all add-ons we recommend.
