### ISSUE TITLE
Underlines doesn't show for words which can hover

### ISSUE THREAD

**Issue by M-Azuma** [mass-immersion-approach/MIA-Japanese-Add-on#44]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
I am using [Mini Format Pack](https://ankiweb.net/shared/info/295889520) to add some styles to the word. Bold and italic can be applied normally, but underline doesn't appear.
Other words that aren't annotated with `[]` can be underlined normally.

### Card
![image](https://user-images.githubusercontent.com/3676278/71243944-64920800-234c-11ea-8f82-675259abf530.png)

### Preview
![image](https://user-images.githubusercontent.com/3676278/71243930-5ba13680-234c-11ea-9e75-8c073634f08b.png)

**Comment by LucasMIA** [comment]
We have no plans to ensure that our custom formatting with work with every single other type of formatting possible. If you would like to attempt to fix this issue and open a pr than I would be happy to review and accept it.
