### ISSUE TITLE
Cannot add notes with type "MIA Japanese" because of JavaScript in template

### ISSUE THREAD

**Issue by gorgonical** [mass-immersion-approach/MIA-Japanese-Add-on#45]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Slackware Linux Current
  - Anki version: 2.1.17 (4cead7ef)

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
It is impossible to add cards using the provided MIA Japanese note type. Upon filling in a card such as "お茶” for expression, "tea" for meaning, and clicking the word-fill button to provide audio,  the error message "the provided input would give an empty question on all cards" and can be resolved by removing the entire JS block in the front side. I don't know what could be wrong with the code, but the card template does not like it.

**Comment by LucasMIA** [comment]
This was an issue with Anki 2.1.17 - 2.1.19, the Anki developer has fixed this issue in 2.1.20.

**Comment by LucasMIA** [comment]
I should add that the issue you were seeing was not due to the JS but rather was due to the broken conditional replacement feature in Anki itself, you can test this by attempting to use that feature with any card type in Anki versions 2.1.17 - 2.1.19.
