### ISSUE TITLE
Customize colors for light/dark mode

### ISSUE THREAD

**Issue by JHerseth** [mass-immersion-approach/MIA-Japanese-Add-on#48]
**Type:**
  - [ ] bug
  - [x] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Win10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
With Dark Mode comming to native anki, would it be posible to customize the colors for light and dark mode respectively?

**Comment by LucasMIA** [comment]
Allowing this sort of customization would raise the complexity of the add-on more than we aiming to.

**Comment by JHerseth** [comment]
How about making it just configurable through the config.json? All it takes is a small edit of the getJapaneseCss function.  Would you accept a pull request?
