### ISSUE TITLE
Add-on not available for Anki Version 2.1.26

### ISSUE THREAD

**Issue by Junah-Park** [mass-immersion-approach/MIA-Japanese-Add-on#61]
**Type:**
  - [ ] bug
  - [ ] feature
  - [ ] enhancement
  - [x] question

**Environment:**
  - OS: Windows

**I'm going to open a PR to resolve the issue:**
  - [x] yes
  - [ ] no

**Description:**
I am new to contributing and would like to get this add-on working for the latest version of Anki. I will look through code to figure out how to do so, any guidance would be appreciated.

**Comment by LucasMIA** [comment]
Thanks for your interest in updating MIA Japanese to Anki 2.1.26, however we have a policy of using MIA development cycles for our add-ons. You can find out more about why we use development cycles below. Anyways, we will not be accepting pull requests that change the supported Anki versions until the end of this development cycle. Please note that we also do not allow parallel releases of our add-ons as is so stated in our license. Please reach back out to us as the end date of this development cycle nears, we'd love to have you contribute~!

**MIA Team Development Cycles**
The MIA team develops add-ons in 6-month development cycles. For the duration of a development cycle, we design add-ons for the latest stable version of Anki that was available at the beginning of that cycle. At the end of a development cycle, all MIA add-ons are upgraded to the latest stable version of Anki. 

**Why We Use a Development Cycle:**
      ● By not needing to constantly update add-ons each time a new version of Anki is released, we’re better able to stay focused on new projects.
      ● When everyone is using the same version of Anki and the same version of add-ons, bug fixing can proceed more efficiently.
     ● Because users only have to update their set-up once every 6 months, they can more easily stay focused on their studies.
     ● We surveyed our users and found that the vast majority approved of a 6-month development cycle. 

**Current Cycle Details:**
      Anki Version:  Anki 2.1.22 (Windows and Linux), Anki 2.1.23 (macOS) [The “alternate” variants are for 32-bit systems] 
      Start Date: April 6th, 2020
      Next Cycle Start Date: October 6th, 2020
