### ISSUE TITLE
Please consinder supporting anki 2.1.29

### ISSUE THREAD

**Issue by TFarla** [mass-immersion-approach/MIA-Japanese-Add-on#63]
**Type:**
  - [ ] bug
  - [x] feature
  - [ ] enhancement
  - [x] question

**Environment:**
  - OS:

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
The ankiweb page of this addon states that it supports the following versions:

Supported Anki versions:

- 2.1.14-2.1.16 (updated 2019-12-25)
- 2.1.22-2.1.23 (updated 2020-03-05)

The newest stable release of anki has been deployed on the 28th of July and I'm not able to install this addon on the new stable 2.1.29 version. Please consider supporting this version.

**Comment by LucasMIA** [comment]
MIA Team Development Cycles
The MIA team develops add-ons in 6-month development cycles. For the duration of a development cycle, we design add-ons for the latest stable version of Anki that was available at the beginning of that cycle. At the end of a development cycle, all MIA add-ons are upgraded to the latest stable version of Anki. 

      Why We Use a Development Cycle:
            ● By not needing to constantly update add-ons each time a new version of Anki is released, we’re better able to stay focused on new projects.
            ● When everyone is using the same version of Anki and the same version of add-ons, bug fixing can proceed more efficiently.
            ● Because users only have to update their set-up once every 6 months, they can more easily stay focused on their studies.
            ● We surveyed our users and found that the vast majority approved of a 6-month development cycle. 

      Current Cycle Details:
            Anki Version:  Anki 2.1.22 (Windows and Linux), Anki 2.1.23 (macOS) [The “alternate” variants are for 32-bit systems] 
            Start Date: April 6th, 2020
            Next Cycle Start Date: October 6th, 2020
